version: '3.1'

services:
    test-db:
        image: postgres:14
        restart: always
        environment: 
          POSTGRES_USER: osm_integrator
          POSTGRES_PASSWORD: 12345678
        ports:
            - 2345:5432