version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: osm_integrator
      POSTGRES_PASSWORD: super_compolicated_password_12345